---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ui-ingress
  namespace: {{.Values.NameSpace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.local
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{.Values.Jenkins.Service.Name}}
              port:
                number: {{.Values.Jenkins.Service.Port}}
