{{- if .Values.SecretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name}}-secrets-config
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  provider: {{.Values.SecretProviderClass.provider}}
  parameters:
    objects: |
    {{- range $objects := .Values.SecretProviderClass.objects }}
      - objectName: {{ $objects.objectName | quote}}
        objectType: {{ $objects.objectType | quote}}
    {{- end }}
  {{- end }}